config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'comments/index'
  end
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'homes/about', to: 'homes#about', as: 'about'
  resources :users, only: [:show, :edit, :update]
  resources :recipes
  get 'mypage', to: 'users#mypage'
  resources :users do
    member do
      delete 'destroy_account', to: 'users#destroy', as: 'destroy_account'
    end
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :following
      get :followers
    end
  end

  resources :recipes do
    resource :favorite, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  get "search" => "searches#search"

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
  end

  resources :groups
  resources :favorites

  resources :groups do
    post 'accept_invitation', on: :member
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_many :invitations

  validates :name, presence: true

  def available_invited_users
    User.joins(:followings).where(followings: {follower_id: users})
  end

  def has_invitation?(user)
    self.invitations.exists?(user_id: user.id)
  end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if params[:search].present?
      @groups = Group.where("name LIKE ?", "%#{params[:search]}%")
    else
      @groups = Group.all
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to admin_groups_path, notice: 'グループを削除しました。'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @recipe = Recipe.new
    @user = current_user
    @groups = @user.groups
  end


  def show
    @recipe = Recipe.new
    @group = Group.find(params[:id])
    @group_users = @group.users
    @recipes = Recipe.where(user_id: @group_users.pluck(:id))
  end

  def new
    @group = Group.new
    @invited_users = @group.available_invited_users
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      if params[:user_ids].present?
        user_ids = params[:user_ids]
        user_ids.each do |user_id|
          @group.users << User.find(user_id)
        end
      end
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to '/mypage', notice: "グループが削除されました"
  end

  def accept_invitation
    @group = Group.find(params[:id])
    current_user.groups << @group
    redirect_to groups_path, notice: 'グループに参加しました'
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: []).merge(owner_id: current_user.id)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :users, "メンバーを選択（複数選択可）" %>
    <%= f.collection_select :user_ids,[current_user] + current_user.followers , :id, :name, {prompt: "ユーザーを選択してください"}, {multiple: true, class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.submit '更新する', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>グループ名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= link_to group.name, group_path(group) %></td>
        <% if group.owner_id == current_user.id %>
          <td>
            <%= link_to 'グループ編集', edit_group_path(group), class: "btn btn-sm btn-success" %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
    <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>グループ編集</h3>
        <%= render 'form', group: @group %>
        <% if @group.owner_id == current_user.id %>
          <%= link_to "削除", group_path(@group), method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }, class: 'btn btn-danger' %>
        <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>グループ</h2>
      <%= render 'index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>グループを作成</h3>
        <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3 offset-md-1'>
      <h2><%= @group.name %></h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>グループメンバー一覧</th>
          </tr>
        </thead>
        <tbody>
          <% @group_users.each do |user| %>
            <tr>
              <% if current_user == user %>
                <td><%= link_to user.name, mypage_path %></td>
              <% else %>
                <td><%= link_to user.name, user_path(user) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% if @group.owner_id == current_user.id %>
        <%= link_to 'メンバー編集', edit_group_path(@group), class: "btn btn-sm btn-success" %>
      <% end %>
    </div>
    <nav class="navbar navbar-light bg-light sticky-top justify-content-end">
      <a href="/recipes/new" id="new-recipe-link" class="navbar-brand">
        <i class="fas fa-pen-to-square">レシピを書く</i>
      </a>
    </nav>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 justify-content-center">
      <% @recipes.each do |recipe| %>
        <%= render partial: 'recipes/recipe_card', locals: { recipe: recipe } %>
      <% end %>
    </div>
  </div>
</div>